### ISSUE TITLE
Step fails if lane name contains space

### ISSUE THREAD

**Issue by ofalvai** [bitrise-steplib/steps-fastlane#82]
### Troubleshooting

- [X] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? latest
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Issue description

Step fails if the provided Fastlane lane contains spaces, for example `ios refresh_dsyms`

### Steps to reproduce

1. Create a Fastlane setup with a lane called that contains spaces
2. Add this step to workflow
3. Specify the lane name
4. Run

**Comment by chedabob** [comment]
I'm unable to reproduce this. Do you have a sample Fastfile and Bitrise.yml?

I have this in my bitrise.yml to test
```
broken_spaces:
    steps:
    - path::./:
        title: Test for spaces in lane name
        inputs:
        - lane: ios test
        - work_dir: ./
        - verbose_log: "yes"
```

And my Fastfile

```
platform :ios do
  desc "Description of what the lane does"
  lane :test do
    puts "!!!Lane with spaces"
  end
end
```

And I can see it has run in the console output

<img width="651" alt="image" src="https://user-images.githubusercontent.com/168025/136279168-e24bc8c3-e333-42bb-8d88-9c1d41c3e71e.png">
